version: '2'

services:
    mysql:
        image: mysql:5.7.16
        container_name: f_mysql
        restart: always       
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
        ports:
            - "3306:3306"
